//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_yachts.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int IdInvoice { get; set; }
        public int IdContract { get; set; }
        public bool Settled { get; set; }
        public decimal Sum { get; set; }
        public double SumInclVat { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
