//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_yachts.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_boat
    {
        public int IdBoat { get; set; }
        public string Model { get; set; }
        public string NameBoatType { get; set; }
        public int NumberOfRowers { get; set; }
        public bool Mast { get; set; }
        public string NameColour { get; set; }
        public string NameWood { get; set; }
        public int BasePrice { get; set; }
        public double VAT { get; set; }
    }
}
