//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_yachts.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_order
    {
        public int IdOrder { get; set; }
        public System.DateTime Date { get; set; }
        public string FullNameSalesPerson { get; set; }
        public string FullNameCustomer { get; set; }
        public string Model { get; set; }
        public string SelectedAccessoriesAtOrder { get; set; }
        public string DeliveryAddress { get; set; }
        public string City { get; set; }
    }
}
